=== NASA-AMMOS/MMTC/mmtc-core/src/test/resources/TkPacketTests/PacketDefs/tk_packet.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="mmtc" xmlns="mmtc">

    <!-- MMTC Schema that defines a telemetry packet contents -->
    <xs:element name="Packet_Definition" type="Packet_DefinitionType" />
    <xs:complexType name="Packet_DefinitionType">
        <xs:sequence>
            <xs:element ref="TelemetryPoint" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:element name="TelemetryPoint" type="TelemetryPointType" />
    <xs:complexType name="TelemetryPointType">
        <xs:sequence>
            <xs:element ref="name" />
            <xs:element ref="offset" />
            <xs:element ref="length" />
            <xs:element ref="type"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="name" type="xs:string" />
    <xs:element name="offset" type="xs:int" />
    <xs:element name="length" type="xs:int" />
    <xs:element name="type" type="xs:string"/>
</xs:schema>

=== NASA-AMMOS/MMTC/mmtc-plugin-ampcs/src/test/resources/test_tk_pkt.xml
<?xml version="1.0"?>

<!--

Fabricated definition of a notional time correlation packet.

All offsets are in bits from the beginning (bit 0) of the packet. All lengths are in bits. All data
types are unsigned integers.

-->

<Packet_Definition
        xmlns="mmtc"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="mmtc tk_packet.xsd">

    <!-- Bit 0 Timestamp (seconds), Coarse part of SCLK associated with the target frame, but contained in the current frame -->
    <TelemetryPoint>
        <name>SclkCoarse</name>
        <offset>48</offset>
        <length>32</length>
        <type>UNSIGNED_INT</type>
    </TelemetryPoint>

    <!-- Bit 0 Timestamp (subseconds), Fine part of SCLK associated with the target frame, but contained in the current frame -->
    <TelemetryPoint>
        <name>SclkFine</name>
        <offset>80</offset>
        <length>16</length>
        <type>UNSIGNED_INT</type>
    </TelemetryPoint>

    <!-- Last SCLK Missed Flag (Indicates invalid data if bit is set) -->
    <TelemetryPoint>
        <name>InvalidFlag</name>
        <offset>200</offset>
        <length>1</length>
        <type>UNSIGNED_INT</type>
    </TelemetryPoint>

    <!-- Last Frame VCID (Virtual Channel ID of the target frame) -->
    <TelemetryPoint>
        <name>TargetFrameVcid</name>
        <offset>208</offset>
        <length>6</length>
        <type>UNSIGNED_INT</type>
    </TelemetryPoint>

    <!-- Last Frame VCFC (Virtual Channel Frame Count of the target frame) -->
    <TelemetryPoint>
        <name>TargetFrameVcfc</name>
        <offset>214</offset>
        <length>24</length>
        <type>UNSIGNED_INT</type>
    </TelemetryPoint>

    <!-- Last Frame Encoding Mode (Encoding method of the target frame) -->
    <TelemetryPoint>
        <name>EncodingMethod</name>
        <offset>238</offset>
        <length>8</length>
        <type>UNSIGNED_INT</type>
    </TelemetryPoint>

</Packet_Definition>
